
package service.AAADEVAmericasBPS.SOAP.org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SaludTotalService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://apps.americasbps.com/ST_IVR/SaludTotalService.asmx?WSDL")
public class SaludTotalService
    extends Service
{

    private final static URL SALUDTOTALSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALUDTOTALSERVICE_EXCEPTION;
    private final static QName SALUDTOTALSERVICE_QNAME = new QName("http://tempuri.org/", "SaludTotalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://apps.americasbps.com/ST_IVR/SaludTotalService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALUDTOTALSERVICE_WSDL_LOCATION = url;
        SALUDTOTALSERVICE_EXCEPTION = e;
    }

    public SaludTotalService() {
        super(__getWsdlLocation(), SALUDTOTALSERVICE_QNAME);
    }

    public SaludTotalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALUDTOTALSERVICE_QNAME, features);
    }

    public SaludTotalService(URL wsdlLocation) {
        super(wsdlLocation, SALUDTOTALSERVICE_QNAME);
    }

    public SaludTotalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALUDTOTALSERVICE_QNAME, features);
    }

    public SaludTotalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaludTotalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SaludTotalServiceSoap
     */
    @WebEndpoint(name = "SaludTotalServiceSoap")
    public SaludTotalServiceSoap getSaludTotalServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SaludTotalServiceSoap"), SaludTotalServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaludTotalServiceSoap
     */
    @WebEndpoint(name = "SaludTotalServiceSoap")
    public SaludTotalServiceSoap getSaludTotalServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SaludTotalServiceSoap"), SaludTotalServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALUDTOTALSERVICE_EXCEPTION!= null) {
            throw SALUDTOTALSERVICE_EXCEPTION;
        }
        return SALUDTOTALSERVICE_WSDL_LOCATION;
    }

}
